version: "3.8"

services:
  web:
    build: .
    container_name: iclinic_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/src:z
    ports:
      - ${APP_PORT}:8000
    depends_on:
      - db
      - redis_dev
  db:
    image: postgres:13
    container_name: iclinic_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/:z
    ports:
      - 5432:5432
  redis_dev:
    image: redis:alpine
    container_name: iclinic_redis
    expose:
      - '6379'
    ports:
      - '6379:6379'

volumes:
  postgres_data: