# Generated by Django 3.1.6 on 2021-02-13 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.IntegerField(help_text="Clinic's identification number", primary_key=True, serialize=False, verbose_name='Clinic ID')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.IntegerField(help_text="Patient's identification number", primary_key=True, serialize=False, verbose_name='Patient ID')),
            ],
        ),
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.IntegerField(help_text="Physician's identification number", primary_key=True, serialize=False, verbose_name='Physician ID')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Prescription', max_length=100, verbose_name='Prescription')),
                ('date', models.DateTimeField(auto_now=True, help_text='Prescription date', verbose_name='Prescription Date')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescriptions.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescriptions.patient')),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescriptions.physician')),
            ],
        ),
    ]
